### ISSUE TITLE
There is an error in IDE Fatal Errors

### ISSUE THREAD

**Issue by koraLi** [manifold-systems/manifold#269] opened 2021-05-17 07:05 UTC
I don't know how this happened,but it doesn't seem to affect the running.

ide: IntelliJ IDEA 2020.2.3 (Ultimate Edition)
jdk: 1.8
system: windows 10

![微信截图_20210517150032](https://user-images.githubusercontent.com/19795190/118445723-6585bf80-b721-11eb-9336-36ea77ac7bd7.png)

**Comment by koraLi** [comment] 2021-05-17 10:02
provider: manifold.ij.extensions.ManPropertiesAugmentProvider@771c934a

java.lang.NullPointerException
	at manifold.ij.core.ManModule.hasJar(ManModule.java:70)
	at manifold.ij.core.ManModule.lambda$new$3(ManModule.java:65)
	at manifold.util.concurrent.LocklessLazyVar$1.init(LocklessLazyVar.java:90)
	at manifold.util.concurrent.LocklessLazyVar.get(LocklessLazyVar.java:40)
	at manifold.ij.core.ManModule.isPropertiesEnabled(ManModule.java:414)
	at manifold.ij.extensions.ManPropertiesAugmentProvider.getAugments(ManPropertiesAugmentProvider.java:54)
	at com.intellij.psi.augment.PsiAugmentProvider.lambda$collectAugments$2(PsiAugmentProvider.java:119)
	at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:200)
	at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:118)
	at com.intellij.psi.impl.source.PsiModifierListImpl.getAnnotations(PsiModifierListImpl.java:276)
	at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.applyAnnotations(JavaSharedImplUtil.java:84)
	at com.intellij.psi.impl.source.PsiTypeElementImpl.calculateType(PsiTypeElementImpl.java:154)
	at com.intellij.psi.impl.source.PsiTypeElementImpl.lambda$getType$0(PsiTypeElementImpl.java:67)
	at com.intellij.psi.util.CachedValuesManager.lambda$getProjectPsiDependentCache$0(CachedValuesManager.java:132)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:153)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:76)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:150)
	at com.intellij.psi.util.CachedValuesManager.getProjectPsiDependentCache(CachedValuesManager.java:131)
	at com.intellij.psi.impl.source.PsiTypeElementImpl.getType(PsiTypeElementImpl.java:67)
	at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.getType(JavaSharedImplUtil.java:38)
	at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.getType(JavaSharedImplUtil.java:34)
	at com.intellij.psi.impl.source.PsiFieldImpl.getType(PsiFieldImpl.java:128)
	at manifold.ij.extensions.ManResolveCache.handleFieldSelfTypes(ManResolveCache.java:170)
	at manifold.ij.extensions.ManResolveCache.resolveWithCaching(ManResolveCache.java:127)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$TypeEvaluator.fun(PsiReferenceExpressionImpl.java:359)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$TypeEvaluator.fun(PsiReferenceExpressionImpl.java:354)
	at com.intellij.psi.impl.source.resolve.JavaResolveCache.lambda$getType$0(JavaResolveCache.java:65)
	at com.intellij.psi.util.CachedValuesManager.lambda$getProjectPsiDependentCache$0(CachedValuesManager.java:132)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:153)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:76)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:150)
	at com.intellij.psi.util.CachedValuesManager.getProjectPsiDependentCache(CachedValuesManager.java:131)
	at com.intellij.psi.impl.source.resolve.JavaResolveCache.getType(JavaResolveCache.java:65)
	at manifold.ij.extensions.ManJavaResolveCache.getType(ManJavaResolveCache.java:75)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.getType(PsiReferenceExpressionImpl.java:421)
	at manifold.ij.core.ManPsiAssignmentExpressionImpl.isOverloaded(ManPsiAssignmentExpressionImpl.java:43)
	at manifold.ij.core.ManPsiAssignmentExpressionImpl.getReference(ManPsiAssignmentExpressionImpl.java:49)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.getReferences(SharedPsiElementImplUtil.java:76)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.getReferences(CompositePsiElement.java:144)
	at com.intellij.psi.PsiReferenceServiceImpl.doGetReferences(PsiReferenceServiceImpl.java:37)
	at com.intellij.psi.PsiReferenceServiceImpl.getReferences(PsiReferenceServiceImpl.java:24)
	at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:32)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.lambda$execute$0(PsiSearchHelperImpl.java:938)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:87)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.lambda$processElementsAtOffsets$0(LowLevelSearchUtil.java:178)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processOffsets(LowLevelSearchUtil.java:204)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:177)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.execute(PsiSearchHelperImpl.java:934)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:275)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:266)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:25)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:25)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processCandidates$18(PsiSearchHelperImpl.java:894)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processVirtualFile$11(PsiSearchHelperImpl.java:538)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1105)
	at com.intellij.openapi.application.ex.ApplicationUtil.tryRunReadAction(ApplicationUtil.java:33)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processVirtualFile(PsiSearchHelperImpl.java:520)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processPsiFileRoots$7(PsiSearchHelperImpl.java:395)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$8(PsiSearchHelperImpl.java:468)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$9(PsiSearchHelperImpl.java:467)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:117)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by rsmckinney** [comment] 2021-05-18 04:36
@koraLi thanks for reporting this. I'm unable to reproduce this.  Does this happen regularly with one of your projects?  Or was it a one off error?

**Comment by koraLi** [comment] 2021-05-18 04:44
I have only one project. It happended 51 times, and there are too many IDE fatal errors. Monitoring stopped.

![微信截图_20210518124023](https://user-images.githubusercontent.com/19795190/118591457-c58a6d80-b7d6-11eb-860e-71741fc86b65.png)

![微信截图_20210518124034](https://user-images.githubusercontent.com/19795190/118591498-d3d88980-b7d6-11eb-8cbb-cc8daa3bddc8.png)

**Comment by rsmckinney** [comment] 2021-05-18 08:28
Does it continue to happen?  Is your project shared on github or similar?

**Comment by koraLi** [comment] 2021-05-19 02:56
It happened twice 29 mins ago. I still don't know how it appeared.

![微信截图_20210519105359](https://user-images.githubusercontent.com/19795190/118749783-c97ac600-b890-11eb-8eef-a8cc19f88850.png)

**Comment by rsmckinney** [comment] 2021-05-20 03:10
Ok, thanks, I'll keep my eye on it

**Comment by sskorol** [comment] 2021-08-19 10:19
@rsmckinney with this [repo](https://github.com/sskorol/manifold-lombok-issue) I'm getting plugin crash (NPE) every time I open the project.

**Comment by rsmckinney** [comment] 2021-08-31 14:16
These issues appear to be fixed in the latest release (2021.2.16).

**Closed by rsmckinney** 2021-08-31 14:16 UTC
Labels: bug
