### ISSUE TITLE
Compile error missing with extension method on generic specialization

### ISSUE THREAD

**Issue by YounesRahimi** [manifold-systems/manifold#27] opened 2018-11-13 08:29 UTC
If We use nested generic types in defining extension methods it will probably generate a wrong return type.
Example:
```java
public static <T> List<T> awaitAll(@NotNull @This Iterable<? extends CompletionStage<T>> thiz) {
return Flux.fromIterable(thiz).flatMap(Mono::fromCompletionStage).parallel(thiz.toList().size()).collectSortedList((t1, t2) -> 1).block();
    }
```

Now if we use this extension:
```java
List<CompletableFuture<SendResult<Long, IngesterData>>> completableFutures = ...
List<CompletableFuture<SendResult<Long, IngesterData>>> actualAndWrongType = completableFutures.awaitAll();
```
While the correct return type must be:
```java
List<SendResult<Long, IngesterData>> wantedAndCorrectType = completableFutures.awaitAll();
```

Even if I use a list of strings, `awaitAll()` accepts it and returns a list of strings:
```java
List<String> strings = Arrays.asList("").awaitAll();
```

If I use direct static method call, I will get correct return type:
```java
List<SendResult<Long, IngesterData>> sendResults = ScIterableExt.awaitAll(completableFutures);
```

**Comment by rsmckinney** [comment] 2018-11-13 20:11
Hi Younes.

At present Manifold supports extensions on generic types, but it does not support extensions for generic *specialization*.  For example, you can write extensions for the generic type `Iterable<T>`, but you can't write an extension targeting only `Iterable<String>`.

Essentially you must not qualify `T` in the receiver parameter (the `@This` parameter), there should be a compiler error indicating this:
```java
// Good
public static <T> void myMethod(@This Iterable<T> thiz) { ... }

// Bad - "? extends List<T>" is not supported
public static <T> void myMethod(@This Iterable<? extends List<T>> thiz) { ... }
```
That said there are no restrictions on the use of `T` in other parameters (not marked with `@This`) and of course you can make generic methods and use method type variables:
```java
// Use T freely in other parameters
public static <T> void myMethod(@This Iterable<T> thiz, Iterable<? extends List<T>> that) { ... }

// Anything goes with R as a method type var
public static <T, R extends List<T>> List<R> foo(@This Iterable<T> thiz, R arg) {...}
```

I'll probably add support for generic specialization in the near future.

For now I'll add a compile error indicating the problem with configuring T in the receiver parameter.

Thanks for reporting this!

**Comment by rsmckinney** [comment] 2019-03-30 20:23
Duplicate of #7

**Closed by rsmckinney** 2019-03-30 20:23 UTC
Labels: bug
