### ISSUE TITLE
Support `Self` type with extension methods

### ISSUE THREAD

**Issue by YounesRahimi** [manifold-systems/manifold#26] opened 2018-11-11 11:26 UTC
Is There any way that we could write extension methods for generic types? For example:
```java
    public static <T> T println(@This T thiz) {
        System.out.println(thiz); 
        return thiz;
    }
```

Or 
```java
    public static <T extends Collection<? extends Long>> T printMax(@This T thiz) {
        System.out.println(thiz.max(Long::compareTo));
        return thiz;
    }
```

Thanks again for this awesome library.

**Comment by rsmckinney** [comment] 2018-11-11 21:35
Extension methods do support generic types.  For instance, you can write an `Iterable` extensions like this:
```java
package extensions.java.lang.Iterable;

public static <T> T first(@This Iterable<T> thiz) {
  . . .
}
```
In your examples, however, you attempt to extend a type variable `T`, which is not an addressable type.

The essence of what your example methods accomplish is called the `Self` type.  The `Self` type is used primarily to support covariance on return types declared in a superclass.  Java does not support the `Self` type, however it can be accomplished indirectly via recursive generic types.  For example, if `java.lang.Object` were to provide your `println()` method it would do so as a recursive type:
```java
public class Object<T extends Object<T>> {
  public T println() {
    System.out.println(thiz); 
    return thiz;
  }
}
```
As such a subclass of `Object` is declared like this:
```java
public class MyClass extends Object<MyClass> { 
}
```
Now you can call `println()` with covariance:
```java
MyClass myClass = new MyClass();
myClass = myClass.println(); // return type is MyClass
```
If Java supported the `Self` type, you could achieve the same thing without resorting to generics:
```java
public class Object {
  public Self println() {
    System.out.println(thiz); 
    return thiz;
  }
}
```
Now this begs the question, can Manifold provide Java with the `Self` type?  I believe so.  This will be an interesting feature to implement...

**Comment by rsmckinney** [comment] 2018-11-22 09:30
Fixed with af9746b

Watch the [Self Type](http://manifold.systems/docs.html#the-self-type) documentation for details

**Closed by rsmckinney** 2018-11-22 09:30 UTC
Labels: enhancement

**Comment by rsmckinney** [comment] 2018-11-24 22:50
Hi Younes.  

This is by design; the `@Self` annotation is limited to a method's return type (for now).  The compiler produces an error message if used elsewhere. 

A key difference with Manifold's self type is although `@Self` targets the method declaration, it resolves at the method _call site_ -- the best of both worlds.  As a consequence it avoids the barrel of monkeys that is Java method bridging and, importantly, it enables more flexibility with the type system in terms of method signature variance and generics.  This opens the door to type-safe usages in methods like `Object#equals(Object)` -- with `@Self` you could instead define it as: `Object#equals(@Self Object)` where you can override the method using the same `@Self Object` parameter type, but still have the compiler enforce the subclass type for arguments to the method as well as enforce subclass treatment of the parameter in the method body.  This feature will be available in a future release.

**Comment by rsmckinney** [comment] 2019-03-10 04:15
UPDATAE:

`@Self` has been rewritten to fully support the *Self* type.  Use it in method return types, parameter types, and field types.  [Learn more](http://manifold.systems/docs.html#the-self-type).

Note the Manifold IntelliJ plugin is currently awaiting approval from JetBrains,.  The plugin alpha release, 0.47-alpha, will be available from Intellij soon.
