### ISSUE TITLE
When source code has errors: The Manifold plugins makes IntelliJ very slow (delay of 7 to 13s!) 

### ISSUE THREAD

**Issue by schittli** [manifold-systems/manifold#290] opened 2021-09-05 20:21 UTC
I'm very sorry, keep writing about issues, I find manifold actually brilliant.

## Describe the bug
For some days, I noticed that IntelliJ becomes very slow as soon as the code has errors. 

Now, unfortunately, I was able to trace the problem back to the manifold plugin: 

### Ex. 1: No optional IJ Plugins are enabled: IJ is fast
I finally had time to disable all plugins - and then IJ is fast, see this example: I fix a bug in my code and return a string in the Code. You can see the characters while typing the returned string content:

![IntelliJ, without optional plugins](https://user-images.githubusercontent.com/8282673/132139704-fc4af932-070f-4875-b4d6-55e6ff7dc00e.gif)

### Ex. 2: Just the Manifold Plugin 2021.2.17 is enabled: IJ gets lags
Now, I just enable the Manifold Plugin, 2021.2.17 (I'm pretty sure this bug crept in **before** version 2021.2.16). I fix the same bug in my code as above and return a string. 
**Maybe important:** As soon as I start modifying `null` in `"null"`, then IJ is blocked. Now, you can not see typing the characters in the returned string. After a delay of about 11s the complete return statement is displayed:

![IntelliJ, just with manifld plugin](https://user-images.githubusercontent.com/8282673/132140158-72a79086-29b7-4cef-b58a-b074aa07220c.gif)

**To Reproduce**
1. I have sourcefiles with errors

**Desktop (please complete the following information):**
- OS Type & Version: Windows 10, 21H1, x64
- Java/JDK version: 1.8.0_162
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ IDEA 2021.2 (Community Edition)
Build #IC-212.4746.92, built on July 27, 2021
- Manifold version: 2021.2.17
- Manifold IntelliJ plugin version: 2021.1.16

Kind regards, Thomas

**Comment by rsmckinney** [comment] 2021-09-06 01:24
Hi @schittli.  No problem, happy to fix bugs. Thanks for reporting them.

I can't readily reproduce the lag, it works fine for me.   I wonder if your project is large and perhaps requires a bit more memory?  You can experiment with memory settings in the menu:  `Help | Change Memory Settings`

**Comment by rsmckinney** [comment] 2021-09-06 01:27
Also, it would help if you can provide the manifold dependencies your project uses.  Copy/paste from your maven/gradle build is best.

**Comment by schittli** [comment] 2021-09-06 16:13
Hello @rsmckinney 

Thank you for your feedback and suggestions!, 
just to note it: I have updated the Plugin to 2021.2.18

#### IJ Memory (Help » Change Memory Settings)
- In the past, in my IJ I had set to use 1750 MiB 
- Today, I changed it to use 10000 MiB 
Unfortunately, the behaviour of the lag has not changed, it has about the same duration.


#### In the meantime, I have noticed that:
1. I have the lag not only with errors in the source code but also during normal work with IJ. But then I cannot force the error, it just happens quite often (every few minutes) and most often if I change string content: `"string-content"`
2. As you know, if I fix a string return statement (as described above), then I always / still have the lag.
3. But if I fix simple missing return statements for e.g. booleans, numbers, ..., like in this code: `public boolean test() { }` then I do _not_ have the lag.


#### maven/gradle build
I don't know the build configuration in detail (I just had imported an existing eclipse-project), but because I didn't find a .gradle / *.gradle file, I guess I'm working with maven. After all I load Manifold via maven into my project :-)

My project has:
- 4 modules (with 98% of all the code files) _without_ manifold references.
- 1 **module called 'nehemia'** with manifold references

I have found these configuration files that refer to manifold:
- .idea\libraries\systems_manifold_manifold_exceptions_2021_1_16.xml
- \nehemia\nehemia.iml

I have added both files in this zip file:
[Project-Config-Files.zip](https://github.com/manifold-systems/manifold/files/7117030/Project-Config-Files.zip)

#### If it would help if you could look at the problem in my IDE
Then I could take a snapshot of the computer with my IDE (it's a virtual machine), then you could access it with AnyDesk (I have the license) and experiment freely without anything being able to break. 

I could also just briefly show you the project / problem, then you could act with or without me. 
I just have to have the promise that you do not copy the commercial library, which I can use for free. I'm pretty sure that's not a problem, but I have to mention it anyway.

Thanks a lot, kind regards,
Thomas

**Comment by rsmckinney** [comment] 2021-09-07 03:30
Thanks for all the effort in providing info for this, much appreciated. The zip file should be all I need to begin building a performance test.  If nothing comes of the test, I may need your help regarding access to a snapshot of your vm.  Cheers.

**Comment by rsmckinney** [comment] 2021-09-09 16:18
@schittli I have not been able to reproduce this issue, even with a large project using the same manifold dependencies. So, at this point it is probably best if I examine your project directly. Let's schedule a time when/if convenient for you.

By the way, from the config files you included, it appears your project is neither Maven nor Gradle, but is instead an IntelliJ project. I assume there is no command line build environment for this.  Is that correct?

**Comment by schittli** [comment] 2021-09-09 20:18
Good evening @rsmckinney 
I had hoped that the problem would be easily reproducible and solvable. Now I have just taken a snapshot of the virtual machine and I can still reproduce it.

> By the way, from the config files you included, it appears your project is neither Maven nor Gradle, but is instead an IntelliJ project. I assume there is no command line build environment for this. Is that correct?

Yes, you're right, I do not have a command-line build environment.
This actually also fits to the developer of the framework I use: they have been developing software with Java for 30 years and new technologies always take a long time to be integrated.
Therefore it's probably a 'pure' IntelliJ project, but I can use Maven to add Libraries 😃.


I think scheduling a time is not that difficult. In the next few days, I should be able to organise myself quite well most of the time. Most of the time, I am online from 10:00 to 24:00 / 10am to 12pm (total 14 hours). Of course, if we plan it, I can do it sooner or later.

Therefore, I send you a **link with my 10am timestamp** to a website that allows to change the Timezone and the timestamp is adjusted :-): https://dateful.com/eventlink/3604668873
The almost invisible link offers to select your timezone:

![image](https://user-images.githubusercontent.com/8282673/132754498-b60d3aa4-1253-4437-a35e-4dccf2b1adce.png)


(For me, 3 hours earlier than 10am would be much easier to do than 3 hours later than 12pm.)

**Comment by schittli** [comment] 2021-09-09 20:23
If we have a scheduled time, then I could send you a Microsoft Teams invitation, then we could get started with that. 
All you will need for access is the AnyDesk Client (https://anydesk.com/en). You do not need to install the client / it does not change your system. You will have admin rights on the virtual machine.

**Comment by shoaniki** [comment] 2021-09-11 15:03
I'm seeing what I think is the same issue, although my delays are much longer – one just literally lasted 10 minutes (admittedly on an M1 MBA, so not the fastest computer around).

I'm not sure how easily I can share code -- hopefully looking at @schittli's project will be sufficient -- but I've been playing around and I do have a couple of observations:

  - It's definitely related to project size.  The module I've been adding Manifold features to is part of a reasonably large project (~3m lines).  If I open it by itself, everything is wonderfully fast.
  - It may be related to `ManifoldPsiClassCache`; the threads doing Manifold things seem to spend a significant proportion of their time waiting to call `_getPsiClass()`.  Or that might be a red herring, I can't really claim to know what I'm talking about after half an hour staring at profilers 😅

For now I can work around this by just not opening the entire codebase at once, but it'd be great if you can get to the bottom of it and I'd be very happy to do more experiments or share profiler captures if that would be helpful at all.

**Comment by rsmckinney** [comment] 2021-09-11 18:19
Hi @shoaniki.  Please do share your profiler snapshots, that would be great!

**Comment by shoaniki** [comment] 2021-09-12 16:08
Sure, here's one – this pause was triggered by selecting `.get(` in `map.get(key)` and pressing `[`.  VisualVM format.

[manifold-intellij-pause.nps.zip](https://github.com/manifold-systems/manifold/files/7149877/manifold-intellij-pause.nps.zip)

The three threads that appear to be running Manifold code appear to be blocking each other a lot – thread view during the pause looks like this:

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/17623930/132994760-581a5222-e73b-4a2e-9b1a-486ade7d7d4c.png">

**Comment by rsmckinney** [comment] 2021-09-13 13:23
Thanks! I’ll look at this tonight.

**Comment by rsmckinney** [comment] 2021-09-13 13:45
@schittli if i can’t resolve the issue from the profiler snapshots from @shoaniki, I’ll circle back to you for vm access, if that’s still possible. Thanks for your patience, time is pretty tight for me lately.

**Comment by schittli** [comment] 2021-09-14 20:35
Hello @rsmckinney 

Thank you very much, yes, no problem, I will keep an eye on this issue and keep the VM snapshot until you write to me again or I see that you were able to solve it.

I hope that you will be able to find the problem with the profiler, I wish you good success.

**Comment by djchapm** [comment] 2021-09-17 01:01
I'm fairly new to manifold and now on a project that uses it - my intellij is locking up as well - I increased to 10G memory for intellij which is kind of nuts.  The schema class generated from our graphql in the target directory is over ~250K lines long.  The schema is about 11.6K lines long.  I'm wondering if that is the issue with intellij.  Any of you others having this problem also have large schemas?

**Comment by rsmckinney** [comment] 2021-09-17 03:26
Hi @djchapm.  That's a big graphql schema. I've been meaning to slim down the generated graphql schema and query classes on the order of 10x or more.  I'm hoping perhaps most of the issues relating to the lag on some large codebases is the sheer size of some of the generated schema classes, graphql or otherwise.  Stay tuned.

**Comment by rsmckinney** [comment] 2021-09-27 01:39
@schittli you mentioned in your original post here that you're pretty sure the bug crept in prior to 2021.2.16. Would you mind verifying that when you have time?  I can assist with getting the version from JB marketplace.

**Comment by schittli** [comment] 2021-09-28 20:51
Hello @rsmckinney,

> @schittli you mentioned in your original post here that you're pretty sure the bug crept in prior to 2021.2.16. Would you mind verifying that when you have time? I can assist with getting the version from JB marketplace.

Yes, I'm happy to do that, which two version (plugin and manifold) should I use to test it?

**Comment by rsmckinney** [comment] 2021-09-29 00:00
Excellent @schittli. The object is to find the last release not having the bug, so I would say start with 2021.2.16 and work backwards until it's gone.  Sound good?

**Comment by djchapm** [comment] 2021-09-29 14:24
> Hi @djchapm. That's a big graphql schema. I've been meaning to slim down the generated graphql schema and query classes on the order of 10x or more. I'm hoping perhaps most of the issues relating to the lag on some large codebases is the sheer size of some of the generated schema classes, graphql or otherwise. Stay tuned.

You're latest update really improved the class size for our generated schema.  Playing with it now but I believe this should really reduce the strain on Intellij:
Version 2021.1.20: 272,420 bytes for schema.class
Version 2021.1.23: 123,088 bytes for schema.class

**Comment by rsmckinney** [comment] 2021-10-04 14:54
Good news.

I have identified what appears to be the primary performance issue. Working on a change that should make this issue go away, available in the next release sometime this week.

**Comment by djchapm** [comment] 2021-10-06 18:46
I think we're good - the plugin (v2021.2.25) worked after clearing the intellij Cache, on Mac it is:
 rm -rf ~/Library/Caches/JetBrains/*
This also works if you find Jetbrains getting confused after moving around and loading/unloading maven projects.
I'll be sure to update to 26 when it's avail.

**Comment by schittli** [comment] 2021-10-09 19:42
Good evening @rsmckinney 

> is your project using the manifold-props dependency?

Yes, my project has 5 modules and just the module `nehemia` is referencing / using manifold.
It uses:
* systems.manifold.props
* systems.manifold:manifold-exceptions
* systems.manifold:manifold-ext

![image](https://user-images.githubusercontent.com/8282673/136671898-d3be44eb-d5a0-407a-83ec-686577802fc0.png)

**Comment by schittli** [comment] 2021-10-09 20:17
Hello @rsmckinney 
**Maybe, I have an important note:**

If I test with the Manifold IJ Plugin 2021.2.16, 
then I have this long delay if I modify code in a module that does _not_ reference Manifold.

I mention it because in my first thought I would have expected the manifold processor/compiler to either be inactive in modules without a manifold reference, or it can finish its work very quickly.
On further reflection, however, it could of course be that the Manifold processor/compiler can have a lot of work to do even in modules without a Manifold reference, because of all the possible dependencies, e.g. inheritance.

Maybe the hint is useful anyway 😄

**Comment by djchapm** [comment] 2021-10-11 16:35
Sure!  Really impressed with your quick support and turnaround - these changes are really improving our dev efficiency.

**Comment by rsmckinney** [comment] 2021-10-11 23:27
thanks @schittli.  5s is still bad.  My tests must be exercising different code paths, I'm down to ~1-2s. Also, just a sanity check, are you warming up the VM before testing? Can yo describe the test in terms of the types and expression[s] involved. Again, thanks for you help.

**Comment by schittli** [comment] 2021-10-12 17:22
Hello @rsmckinney 

I'm afraid I need a little more information to provide more details.
> are you warming up the VM before testing?

I was actually hoping so, but I'm not sure.... I tested like this:
1. I prepared the test in IJ by adjusting the manifold references
2. I rebuild the whole project so that the compiler doesn't suddenly realize that it still has work to do
3. I restarted IJ and waited until IJ got idle (e.g. the index scanner, in the beginning, stopped working)
4. Then I started the measurements but I ignored the first two or three results

**Comment by schittli** [comment] 2021-10-12 17:32
### Can you describe the test in terms of the types and expression[s] involved. 

Here I am not sure what you are referring to specifically. I have always done the same test as I [described while creating the ticket](https://github.com/manifold-systems/manifold/issues/290#issue-988590431):

I have this Code:
```
  @Override
  public String format(Object obj, FormatContext formatContext) {
    if (obj == null) {
      return "";
    }
    return null;
  }
```
and then I start typing a String to replace the returned value in the last line:
```
    …   
    return "kl fkas fkjfh kjfh kajhfa kj";
  }
```

So I measure the time from the start of typing until IJ gets the CPU and can display the typed string.

**Comment by schittli** [comment] 2021-10-12 17:35
To allow my code to compile without the remote manifold components, I modified my code to explicitly catch exceptions, for example.

If you have any ideas on what I can test, please let me know.

**Comment by schittli** [comment] 2021-10-15 23:23
Side note:
Just to be sure that we don't hunt a ghost:
* I did the test again without the Manifold IJ plugin and only with the linked manifold-ext module. I repeated the test more than 10x and I never had a delay.
* I removed all old and all unused Maven Manifold files in my `.\maven\` directory - so there is no false reference in the project.

Unfortunately, I still have the problem.

> **Does your project's use of manifold dependencies follow the general practice of declaring manifold-xxxx-rt as implementation and manifold-xxxx dependencies as annotationProcessor?** 

I use maven and the IJ Help explains in [Configure annotation processors﻿](https://www.jetbrains.com/help/idea/2021.2/annotation-processors-support.html?utm_source=product&utm_medium=link&utm_campaign=IC&utm_content=2021.2):

> _"When you add annotation processors through the build scripts in Maven or Gradle projects, IntelliJ IDEA automatically enables the annotation processing and adds the appropriate paths in the annotation processor settings."_

Therefore, I think that I am not able to manipulate the declaration?

There are no explicitly defined annotation processors in the project settings:
![image](https://user-images.githubusercontent.com/8282673/137563201-a6851cdd-d7b7-4e75-92e2-0a90ec1bf929.png)

> **Can you think of anything else about your project that may contribute to the delays?**

I guess that's what happens to a lot of computer engineers: they study about these kinds of issues all the time in their day-to-day lives, but unfortunately, nothing else came to mind either. The debugger is not running, only IntelliJ.

> **Any other IntelliJ plugins involved?**

I have only the bundled IJ plugins enabled and the Manifold plugin. 
If I disable the Manifold plugin as well, then the delay is no longer present. Therefore I guess it must be the Manifold IJ Plugin creating those delays.

**Comment by schittli** [comment] 2021-10-15 23:31
> **Have you tried disabling the dependencies separately to perhaps single out which one is causing the delays?**

I assume that you are talking about the different manifold modules, right?
Normally I would use these Manifold libraries:
* manidod-props
* manidod-exception
* manidod-ext

In the tests, I have gradually reduced the manifold references until I just had manidod-ext.

💡  Tomorrow morning I will change my code so that I no longer need manifold-ext either.
Then I will also remove this last reference so that I only have the Manifold IJ plugin.
I am very curious about the result of this test.

**Comment by rsmckinney** [comment] 2021-10-16 01:36
@schittli Thanks for spending time on this, very much appreciated.

Couple of things.

1. Regarding annotation processor dependencies, Manifold is _not_ an annotation processor, so you don't need to mess with IJ's annotation processor settings, you can leave it all off. However, some Manifold dependencies do need to be listed in the compiler's annotation processor class path, this is how compiler _plugins_ work. To do that with Maven please have a look at the [manifold-props Setup docs for Maven](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-props#maven), paying special attention to dependency declarations and annotationProcessorPaths. I can help configure your module if you prefer.

2. If I understand correctly, you tried reducing your use of Manifold to just manifold-ext and you still experience the lag. Is that right? So, without manifold-props you still have the lag?

3. As a sanity check I recreated your shallow class hierarchy with your MoneyFormat as a base class with supporting classes stubbed to satisfy the implied API, then tried your test. Worked perfectly for me, zero lag.

4. My next move is to test the theory that the change in 2021.2.16 is the culprit. I'm going to add an option for you to enable/disable the change (the newer one I've since replaced it with) to verify that this is indeed the issue.  At this point I suspect there is something else going on.  I'll let you know when the release is available.

Thanks again for your help and patience.

**Comment by schittli** [comment] 2021-10-16 14:20
Hello @rsmckinney 

I have made some additional basic Tests:

1. If my project just has the Manifold Plugin active in IJ 
   but in my project **none** of my modules references a manifold module (like manifold-ext), then I have no delay. 
   _(This may be logical for you, but I distrust many things at the moment ;-) )_

2. If IJ has the Manifold plugin enabled 
   and my project just references manifold-ext (but there is **no** code using the manifold-ext functions), then I already have the delay.
   _(This may be logical for you, but I wanted to be sure that not my extension methods cause the issue )_

**Comment by schittli** [comment] 2021-10-16 19:40
Hello @rsmckinney 
Regarding to:
#### manifold-props Setup docs for Maven
Here I have inhibitions to change my whole IJ Java project to Maven because I know Maven only in the GUI, fear a lot of effort because I don't know the project in detail but only my own module (one of five).

If you think it's worth the experiment, I'll clone my virtual developer machine and give it a try.

**Comment by schittli** [comment] 2021-10-17 09:31
Hello @rsmckinney 
I would like to mention again the offer that I can give you access to a copy of my virtual developer environment. After a short introduction, you could freely experiment with it, I can even provide it 7x24 and there would be just a few rules. 
I have very few appointments and could pretty much follow you for the introduction.

Of course it would be OK for me if you want to wait until another user can provide additional / different hints.

**Comment by rsmckinney** [comment] 2021-10-20 04:44
Hey @schittli. That sounds perfect. I'm assuming you're in Europe somewhere?  I can work within your time zone when convenient for you. I'd still like to provide the switch to enable/disable the changes we discussed, perhaps I'll get that finished tomorrow then I can schedule an appointment with you, if that works. I had planned to have that completed by now, but another IJ plugin issue cropped up I had to fix.

**Comment by stephanedupont** [comment] 2021-11-10 08:35
@rsmckinney @schittli : what is the status on this? I encounter the same problem, enabling the Manifold Plugin makes everything (like autocompletion, syntax coloration, ...) very slow. I was considering using Manifold for its preprocessor features, but I have to put this on hold because right now it's unusable (it adds a few seconds to everything).

**Comment by rsmckinney** [comment] 2021-11-10 13:52
Hi @stephanedupont. This issue is my next priority.

**Comment by stephanedupont** [comment] 2021-11-10 19:56
> Hi @stephanedupont. This issue is my next priority.

Thank you very much @rsmckinney. Is there a way to install a previous build without this problem so I can evaluate Manifold properly?

**Comment by schittli** [comment] 2021-11-10 21:05
Hello @stephanedupont (CC @rsmckinney)

> (Also, this happens regardless if there are any errors in the source code, so maybe it's not the same problem?)

Yes, you are right, meanwhile, I can also confirm that this problem is not related to source code errors.

**Comment by schittli** [comment] 2021-11-10 21:29
> Yes, you are right, meanwhile, I can also confirm that this problem is not related to source code errors.

Sorry, I am wrong: I just had 63 errors in one File and the delay was about 5x longer than usual.
Therefore I guess that source code errors do not necessarily cause the delay, but they aggravate it.

**Comment by stephanedupont** [comment] 2021-11-11 17:23
Oh, just some additional information: I use Android Studio stable based on IJ 2020.3.1, so my Manifold plugin version is 2020.3.41.

Is it still possible that it's the same problem despite the version number?

Also, I really need to decide if I will use Manifold or not (right now it makes developing hellish because of the lag so I can't use it). Is there an older version without this problem that I can try on 2020.3 branch?

**Comment by stephanedupont** [comment] 2021-11-11 17:49
UPDATE: problem is solved by using version 2020.3.38 instead of 2020.3.41.

**Comment by rsmckinney** [comment] 2021-11-11 18:35
Interesting. I have just begun plowing into this issue again. That release dates back a bit earlier than I had expected.  Thanks for digging!  This helps a lot!

**Comment by rsmckinney** [comment] 2021-11-11 20:50
@stephanedupont can you tell me what version of manifold-preprocessor your project is using?

**Comment by stephanedupont** [comment] 2021-11-11 21:00
@rsmckinney 
```
annotationProcessor 'systems.manifold:manifold:2021.1.30'
implementation 'systems.manifold:manifold-rt:2021.1.30'
annotationProcessor 'systems.manifold:manifold-preprocessor:2021.1.30'
```

(Note that as I reported a few days, if I don't explicitly declare the core dependencies then the syntax is not detected in the IDE.)

Do you want me to try another version?

**Comment by rsmckinney** [comment] 2021-11-11 21:05
That's fine. I fixed that issue in the latest IJ plugin, but of course you can't use that at the moment. I can make another 2020 release for you that has that fix.

Also, just to be clear, did you try plugin version 2020.3.39 before moving to 2020.3.38?  Just trying to isolate the problem.  Thanks

**Comment by stephanedupont** [comment] 2021-11-11 21:07
@rsmckinney Thank you, that would be great! I'm trying this right now, will be back in a few minutes.

**Comment by rsmckinney** [comment] 2021-11-11 21:16
Got it, thanks.  If you have time, knowing the first release that fails for you would help a lot.

**Comment by rsmckinney** [comment] 2021-11-11 21:17
So, if 39 is ok, it's either 40 or 41, based on already knowing 41 is bad for you.

**Comment by stephanedupont** [comment] 2021-11-11 21:32
Well, it's incomprehensible: now even 41 works fine... I tested a few hours ago, activating the plugin meant huge lag, disable the plugin solved it, and now it seems it's not the case anymore and it works fine...

**Comment by rsmckinney** [comment] 2021-11-11 21:35
have you made any other changes to your project since first using 41?

**Comment by stephanedupont** [comment] 2021-11-11 21:35
Nope, none.

**Comment by rsmckinney** [comment] 2021-11-11 21:41
hmm. . .   you may want to check IJ memory usage in case you are near the threshold.

I was going to suggest moving this discussion to a separate issue anyway, since you are using a version of the plugin (2020.3.x) which dates earlier than the issue here and is likely unrelated.  Anyhow, if you do see lag again please file another issue for discussion.

**Comment by stephanedupont** [comment] 2021-11-11 21:43
Yes, thank you.

**Comment by rsmckinney** [comment] 2021-11-11 21:44
Good luck with your evaluation and let me know if you have questions.  Cheers!

**Comment by schittli** [comment] 2021-11-12 22:30
Hello @stephanedupont 
> Is there a way to install a previous build without this problem so I can evaluate Manifold properly?

I have this workaround:

Setup:
1. Install the Manyfold IntelliJ Extension
2. Install the Manifold Modules

Workflow: because I use the Manifold Extension Methods, therefore:

- If I'm writing Manifold Extension Method code, **then I activate the Manyfold IntelliJ Extension**. 
  So the compiler works perfectly and writing the Manifold related code is easy, but I have those delays
- **Otherwise, I disable the Manyfold IntelliJ Extension**. 
  Now, the Editor is fast, but the compiler **think** that there are coding errors and it marks them red as usual - but I can perfectly debug the application :-)

**Comment by stephanedupont** [comment] 2021-11-13 15:38
@schittli Thank you.

**Comment by rsmckinney** [comment] 2021-12-15 05:28
Potential fix available with manifold release 2021.1.34 and IJ plugin release 2021.x.38

**Comment by rsmckinney** [comment] 2021-12-17 15:10
Please reopen if this is not fixed

**Closed by rsmckinney** 2021-12-17 15:10 UTC
Labels: IntelliJ Plugin

**Comment by schittli** [comment] 2022-08-24 20:12
**I think it is fixed!, thank you very much!** 😄 

Good evenin @rsmckinney 

after many months I finally get back to developing SW with java and after two weeks of working, I didn't have this tedious error anymore 😃. I am very happy you were able to fix it, thank you very much!

I also saw that Manifold is now free and so I hope that this licensing is also fair for you. I wanted to recommend Manifold in two commercial projects so that they then buy licenses 😃, but because of this issue here I had to wait and I was also not sure if / which Manifold components you rate as mature. 

Thanks a lot for all your work, kind regards,
Thomas

**Comment by rsmckinney** [comment] 2022-09-10 04:17
@schittli Sorry, I had intended on replying to your message when I saw it, then not sure how it got buried. Anyhow, a lot of changes toward improving performance were made since you've last used manifold, glad to hear it is working better for you.

Yes, the manifold intellij plugin is now FOSS (manifold itself has always been FOSS).

Cheers.
