### ISSUE TITLE
"plug-in not found" using dependency "manifold" instead of "manifold-all"

### ISSUE THREAD

**Issue by cschabl** [manifold-systems/manifold#45] opened 2019-02-21 09:37 UTC
Oracle JDK 8 (1.8.0_131) and Gradle 4.10.3:
```
tasks.withType(JavaCompile) {
    options.compilerArgs += '-Xplugin:Manifold'
    options.fork = true
}

dependencies {
    compileOnly libraries.lombok

    compile group: 'systems.manifold', name: 'manifold', version: '0.45-alpha'
    compile group: 'systems.manifold', name: 'manifold-properties', version: '0.45-alpha'
    compile files("\${System.getProperty('java.home')}/../lib/tools.jar")
}
```
When the tasks `compileJava` or `compileTestJava` are executed the following message is logged:
_plug-in not found: Manifold_

This message is not logged if `manifold-all.jar` is used as dependency.

**Comment by rsmckinney** [comment] 2019-02-21 18:59
HI @cschabl.

This is a bug.  The properties manifold (and some others) were recently moved out from Manifold core into separate modules, in the process the plugin service registry is missing from the META-INF/services.  Fortunately, you can fix this in your project simply by adding the registry file to your project's META-INF/services:

In your `src/main/resources/META-INF/services` directory create a file named `com.sun.source.util.Plugin`.  Edit the file to look like:
```text
manifold.internal.javac.JavacPlugin

```
That's it.

I'll have a general fix for this in the next alpha release.  Thanks for reporting the issue!

**Comment by cschabl** [comment] 2019-02-25 08:26
Hi @rsmckinney , is still get the plugin-not-found message with this work-around.

When switching to the manifold-all dependency, Gradle builds my code containing manifold statements to access properties of a properties file. But IntelliJ marks the following statement as error:

`int idx = VERSION.toLowerCase().indexOf("-snapshot");`

IntelliJ's message is: `Incompatible types. Required: int Found:`
Pressing Ctrl+Q (Quick Documentation lookup) gives me a huge list of overloaded methods.

**Comment by rsmckinney** [comment] 2019-02-25 16:57
Hi @cschabl.  I cannot reproduce this, IJ does not produce an error from your example.  Check the Manifold IJ plugin version.  It should be 0.45-alpha (it matches the Manifold version your project uses).

**Comment by cschabl** [comment] 2019-02-26 10:09
Hi @rsmckinney, I do have the latest version of the IJ plugin.

For some reason javac doesn't have the META-INF directory on the classpath. After adding `compile files("$projectDir/src/main/resources")` to the dependencies, gradle builds my project.

**Comment by rsmckinney** [comment] 2019-03-30 20:06
Hi @cschabl. 

I created a gradle-based project from scratch using the following `build.gradle` file
```groovy
plugins {
    id 'java'
}

group 'com.example'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    // Properties files support
    compile group: 'systems.manifold', name: 'manifold-properties', version: '0.55-alpha'

    // tools.jar dependency (for Java 8 only)
    compile files("${System.properties['java.home']}/../lib/tools.jar")

    testCompile group: 'junit', name: 'junit', version: '4.12'
}

tasks.withType(JavaCompile) {
    options.compilerArgs += '-Xplugin:Manifold strings exceptions'
    options.fork = true
}
```
And the `settings.gradle` file:
```groovy
rootProject.name = 'MyProject'
```

The project builds and executes with no problems.  Try using a similar configuration and let me know if you continue to have problems.  Thanks.

**Closed** 2019-03-30 20:19 UTC

**Comment by wilmerkrisp** [comment] 2019-05-24 11:58
please notice error in compileTestJava
you need add

implementation  'systems.manifold:manifold-all:0.71-alpha'
annotationProcessor  'systems.manifold:manifold-all:0.71-alpha'
testImplementation  'systems.manifold:manifold-all:0.71-alpha'
testAnnotationProcessor  'systems.manifold:manifold-all:0.71-alpha'

Itis solved my problem

**Comment by dalegaspi** [comment] 2021-04-25 16:04
per @wilmerkrisp the last two entries `testImplementation` and/or `testAnnotationProcessor` is important if you need to use the Manifold plugins in unit tests.  for example, for string interpolation you need to add:

```gradle
 testAnnotationProcessor 'systems.manifold:manifold-strings:2021.1.11'
```

the documentation needs to be updated with this information. 😊
