### ISSUE TITLE
Repeated Trial Expired popups in IntelliJ CE

### ISSUE THREAD

**Issue by cyroxis** [manifold-systems/manifold#182] opened 2020-05-19 14:03 UTC
When using the manifold plugin in IntelliJ CE there are occasional popups notifying that the trial is expired. But the plugin continues to work. I originally assumed this was due to the updates that IJ made to their marketplace.

However after updating the Manifold plugin to 2020.1.12 the frequency of these popups as greatly increased to one about every 20-30 min which gets annoying really fast.

IntelliJ CE 2020.1.1
Manifold Plugin : 2020.1.12

**Comment by rsmckinney** [comment] 2020-05-20 03:55
@cyroxis I can't reproduce this locally, can you attach a screenshot of the popup you're receiving?

**Comment by cyroxis** [comment] 2020-05-20 18:19
This is the popup window.
<img width="912" alt="Screen Shot 2020-05-20 at 2 14 40 PM" src="https://user-images.githubusercontent.com/1709029/82482288-a3b3b900-9aa4-11ea-89f5-e2cd94bf207e.png">
It looks the same as the popup that showed up in 2019 that actually disabled the plugin but the plugin is not disabled.

**Comment by rsmckinney** [comment] 2020-06-09 23:57
still can't repro this, should be fixed in IJ latest 2020.1.x

**Comment by cyroxis** [comment] 2020-06-29 19:13
Issue still persists on 2020.1.2.

The timing of the popup seems random. It can occur anywhere from a couple times a day to a couple times an hour.

**Comment by rsmckinney** [comment] 2020-07-02 00:54
@cyroxis Just to keep you informed, I have [open questions](https://jetbrains-platform.slack.com/archives/C5U6ZNG20/p1593472442024300) in the JetBrains slack group regarding this issue.  I can't reproduce locally, so I suspect there are conditions which cause the license screen to display that are independent of plugin code. It's taking them a while to respond.

**Comment by rsmckinney** [comment] 2020-07-28 01:51
Note JetBrains has identified some issues that are likely the cause of the popups reported here:

[IDEA-245166](https://youtrack.jetbrains.com/issue/IDEA-245166)
[IDEA-245167](https://youtrack.jetbrains.com/issue/IDEA-245167)

**Comment by WesleyKhoiVo** [comment] 2020-08-27 17:17
+1 User here. Popup on and plugin disable when use Android Studio 4.0

**Comment by WesleyKhoiVo** [comment] 2020-08-27 17:19
After 30 day trial, popup is on. Can you re-check status JetBrains issue?

**Comment by WesleyKhoiVo** [comment] 2020-08-27 17:22
+1 User here. Popup on and plugin disable when use Android Studio 4.0 (base on IntelliJ IDEA 2019.3.3)
After 30 day trial, popup is on. Can you re-check status JetBrains issue?

**Comment by rsmckinney** [comment] 2020-08-28 00:27
@WesleyKhoiVo I'm working with JetBrains to resolve this. JetBrains is also going to release plugins that are free for CE/AS but paid for Ultimate, unfortunately Manifold is waiting for the underlying support.  I can send you a free month of use if that helps.

**Comment by WesleyKhoiVo** [comment] 2020-08-28 02:34
Hi @rsmckinney , I just make sure the bug ID is still in update status. Thanks your kindness, I still stick with current plugin until IDE will be fixed without the key. You are quick and great supporter 👍

**Closed** 2020-12-19 21:50 UTC
Labels: IntelliJ Plugin, bug
