### ISSUE TITLE
Instanceof Not working with in general

### ISSUE THREAD

**Issue by NextdoorPsycho** [manifold-systems/manifold#382] opened 2022-08-24 18:58 UTC
**Describe the bug**
What im trying to do is create an instanced variable based on a functional check ie:
`if (e.getEntity() instanceof Player p ) {}`
As soon as I type the "p" it just locks up manfold and bricks my IDE while im on that page. While here, I noticed this: https://github.com/manifold-systems/manifold/issues/378 and feel its related

**To Reproduce**
In My case I was making a generic Instance check, 
`    @EventHandler
    public void on(EntityDamageEvent e) {
        if (e.getEntity() instanceof org.bukkit.entity.Player p && !e.getCause().equals(EntityDamageEvent.DamageCause.STARVATION) && hasAdaptation(p)) {
            addPotionStacks(p, PotionEffectType.HUNGER, 5 + getLevel(p), 100, true);
            addPotionStacks(p, PotionEffectType.INVISIBILITY, 1, 50 * getLevel(p), true);
        }
    }` Obviously the use cases are different but I think this is a general non-structural issue  (or im just slow and ignorant on the subject, just trying to be a good boi and report my problems)

**Expected behavior**
Not lock the IDE when declaring an instanceof Variable

**Desktop (please complete the following information):**
- OS Type & Version: MacOS  (13.0 Beta (Ventura) / NON Beta)
- Java/JDK version: JDK 17 (Temurin-17.0.4+8) 
- IDE version (IntelliJ IDEA or Android Studio): Build #IU-222.3739.54, built on August 16, 2022
- Manifold version: systems.manifold:manifold-rt:2022.1.19
- Manifold IntelliJ plugin version: 2022.1.20

**Additional context**
Ill be watching this, let me know if you need anything from me, Here is the project as an example:
https://github.com/VolmitSoftware/Adapt/blob/main/src/main/java/com/volmit/adapt/content/adaptation/hunter/HunterRegen.java
That's AN instance not the only, all the instanced variables are like this
**Stack trace**
Please include a stack trace if applicable
https://pastebin.com/0MueRuw1

**Comment by gscaparrotti** [comment] 2022-08-25 10:03
I don't think that the issue is related to the one I experienced with `istanceof`, but rather with the Pattern Matching feature introduced with [JEP 305](https://openjdk.org/jeps/305).

I also experienced the same issue with the following code trying to use this feature and got the same error with the same stack trace. 

The problem is not there when `instanceof` is used the classic way.

**Comment by rsmckinney** [comment] 2022-08-30 21:40
Fixed with IJ plugin release 2022.1.21 available from JetBrains Marketplace within 48 hours.

**Closed** 2022-08-31 12:17 UTC
Labels: bug
