### ISSUE TITLE
Manifold IntelliJ plugin: NullPointerException breaks IntelliJ Menu Items and Quick Fix suggestion :-(

### ISSUE THREAD

**Issue by schittli** [manifold-systems/manifold#284] opened 2021-08-28 09:00 UTC
Hello

I have just updated to the latest release:

- Manifold version: 2021.1.16
- Manifold IntelliJ plugin version: 2021.2.15

## Describe the bug

Addendum:
I'm afraid that the null pointer exception is probably also causing this problem: the IntelliJ menu suddenly has no menu items:

![image](https://user-images.githubusercontent.com/8282673/131212678-f7458ab0-d134-4eb6-ad61-1ca829687fd2.png)

Therefore, I add the newest Plugin Exceptions:
[Stacktrace1.txt](https://github.com/manifold-systems/manifold/files/7070453/Stacktrace1.txt)
[Stacktrace1-included.txt](https://github.com/manifold-systems/manifold/files/7070454/Stacktrace1-included.txt)
[Stacktrace2.txt](https://github.com/manifold-systems/manifold/files/7070455/Stacktrace2.txt)
[Stacktrace2-included.txt](https://github.com/manifold-systems/manifold/files/7070456/Stacktrace2-included.txt)
[Stacktrace3.txt](https://github.com/manifold-systems/manifold/files/7070457/Stacktrace3.txt)
[Stacktrace3-included.txt](https://github.com/manifold-systems/manifold/files/7070458/Stacktrace3-included.txt)
[Stacktrace4.txt](https://github.com/manifold-systems/manifold/files/7070459/Stacktrace4.txt)
[Stacktrace4-included.txt](https://github.com/manifold-systems/manifold/files/7070460/Stacktrace4-included.txt)

In Issue #281 I had reported some stacktraces with NullPointerExceptions in the Manifold IntelliJ plugin. Today I finally understood the context of why IntelliJ no longer displays these QuickFixes:

![image](https://user-images.githubusercontent.com/8282673/131212246-9ba2db29-a070-4411-a260-19d22a084b9b.png)

As soon as I enable the Manifold IntelliJ plugin, IntelliJ no longer offers the QuickFixes: The Compiler reports the bug, but the Editor does not help to solve it:

![image](https://user-images.githubusercontent.com/8282673/131212284-a0ebd03b-4052-457a-8390-35fb0a0921f0.png)

As soon as I disable the Manifold IntelliJ plugin, QuickFixes starts working again.

## Desktop (please complete the following information):

OS Type & Version: Window 10, 2004, x64
Java/JDK version: 1.8
IDE version (IntelliJ IDEA or Android Studio): IntelliJ IDEA 2021.2 (Community Edition)
Build #IC-212.4746.92, built on July 27, 2021
Registry: analyze.exceptions.on.the.fly=true,
Manifold version: 2021.1.16
Manifold IntelliJ plugin version: 2021.2.15

Thanks a lot, kind regards,
Thomas

**Comment by rsmckinney** [comment] 2021-08-28 16:06
@schittli I was not able to reproduce the stack trace. Please provide the steps to reproduce if you can. Thanks.

**Comment by schittli** [comment] 2021-08-28 19:23
Hi @rsmckinney 
thank you for your answer,
unfortunately, I do not know how I could try to reproduce it: 

- My Project has 5610 java source files 
Unfortunately, 99% of the source files consist of a commercial library, which I am allowed to use for my project for free, so I am not allowed to share the project, only a remote desktop session would be ok
- to get the issues, I just open the project; sometimes, I also start 'rebuild project'

Would it help if I go back with the Manifold IntelliJ plugin and the Manifold versions and note when this behaviour was introduced?

Thanks a lot, kind regards,
Thomas

**Comment by rsmckinney** [comment] 2021-08-29 19:49
A potential fix is in plugin release 2021.2.16, should be available tomorrow morning

**Comment by schittli** [comment] 2021-08-31 09:43
Good Morning @rsmckinney 

**thank you very much!,** 
I'm pretty sure you actually found the & fixed bug!, I started IntelliJ several times and recompiled the project - and IntelliJ no longer reported Manifold Exceptions. 
Congratulations!

But unfortunately, manifold-json is broken now, I'll make a ticket right away.


I have an idea for searching this kind of issue:
With such difficult to reproduce bugs as in this issue, it might be possible for you to deduce from the stack trace what kind of code could trigger the error.

If this is true, then we might be able to find the source of the problem if you can tell us what we should be looking for.

I wish you a good day,
thanks a lot, kind regards
Thomas

**Comment by schittli** [comment] 2021-08-31 09:52
Hello @rsmckinney

**I am very sorry!**
**I unfortunately reported a false alarm in the previous message.**

When I tested your new version, I always had error messages with the code that used manifold-json.

Now when I wanted to describe the problem, the error was gone: no matter what I did: **manifold-json always worked perfectly.**

Thanks a lot, kind regards,
Thomas

**Comment by rsmckinney** [comment] 2021-08-31 14:12
Fixed in release 2021.2.16. Thanks for reporting this issue.

**Closed by rsmckinney** 2021-08-31 14:12 UTC
Labels: IntelliJ Plugin
