### ISSUE TITLE
Operators error

### ISSUE THREAD

**Issue by zcfire2017** [manifold-systems/manifold#564] opened 2024-04-02 09:28 UTC
![image](https://github.com/manifold-systems/manifold/assets/34852479/b25ba986-bc66-4624-8018-77115599c116)
![image](https://github.com/manifold-systems/manifold/assets/34852479/1c758d0a-7fda-4b98-9d6c-c34163a0c99d)
jdk：17

It runs normally, but an error appears

**Comment by rsmckinney** [comment] 2024-04-02 20:17
I can't reproduce the error.

I have a new test project with JDK 17 using manifold-ext/rt as documented.

![image](https://github.com/manifold-systems/manifold/assets/588843/f392ac90-0628-4167-ba2c-25d4f1a71cf4)
![image](https://github.com/manifold-systems/manifold/assets/588843/b025e368-1fed-451a-b4f5-4b856f09fd38)

Is your project available for debugging?

**Comment by zcfire2017** [comment] 2024-04-03 02:19
> Oh wait. . . This has to do with usage of the Chinese (Simplified) Language Pack. Some errors in IJ are filtered where manifold operator overloading applies. This will be fixed in the next manifold IJ plugin release by EOD tomorrow.

Thank you vary much

**Comment by zcfire2017** [comment] 2024-04-03 11:56
@rsmckinney  
![image](https://github.com/manifold-systems/manifold/assets/34852479/f8c8bb72-768f-4017-aa04-d05c7dbc7367)

**Comment by rsmckinney** [comment] 2024-04-03 15:02
Will be fixed be EOD tomorrow. Thanks for reporting these!

**Closed** 2024-04-09 03:21 UTC
Labels: bug, IntelliJ Plugin
