### ISSUE TITLE
Extension method on abstract classes if child implements interface

### ISSUE THREAD

**Issue by aikar** [manifold-systems/manifold#56] opened 2019-03-31 04:20 UTC
Is this possible?  

```java
package EMC.extensions.org.bukkit.event.block.BlockEvent;

import com.empireminecraft.systems.residence.PermsBuilder;
import com.empireminecraft.systems.residence.flags.Flag;
import manifold.ext.api.Extension;
import manifold.ext.api.This;
import org.bukkit.event.Cancellable;
import org.bukkit.event.block.BlockEvent;

@Extension
public class BlockEventExtensions {
    public static <T extends BlockEvent & Cancellable> boolean checkPerm(@This T event, Flag... flags) {
        return PermsBuilder.at(event.getBlock()).cancel(event).check(flags);
    }
}
```

I have an abstract class that children may conditionally implement Cancellable.

i want this extension method to only show up on cancellable.

Though I did end up doing this since it was more useful for me anyways, just curious about the other idea

```java
public static boolean checkPerm(@This BlockEvent event, Flag... flags) {
        PermsBuilder builder = PermsBuilder.at(event.getBlock());
        if (event instanceof Cancellable) {
            builder.cancel((Cancellable) event);
        }
        return builder.check(flags);
    }
```

**Comment by aikar** [comment] 2019-03-31 05:04
```java
public abstract class BlockPistonEvent extends BlockEvent implements Cancellable {}
public class BlockPistonExtendEvent extends BlockPistonEvent {}
```

FYI for example
```java

    @EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)
    public void onBlockPistonRetract(BlockPistonRetractEvent event) {
        if (!event.checkPerm(Flags.PISTON)) {
            return;
        }
    }
```

**Comment by rsmckinney** [comment] 2019-03-31 05:51
Your are essentially asking if method extensions support generic <i>specialization</i>.  The short answer is, no, not yet.  A simple way to explain the difference -- the type of the `@This` parameter *must* be the same type as extended class.  Using your example, if you extend `BlockEvent`, your `@This` parameter must be exactly `BlockEvent`, not `T` or any other variation  Similarly, if you define an extension class for `java.util.List`, the `@This` type must be exactly `List<T>`.  

Generic specialization support loosens this up where the `@This` type may vary with the extended type's generic parameters and/or the extension method's generic parameters (see the [docs](http://manifold.systems/docs.html#generics) for more info on this).

See #7 for the broader request for generic specialization support, which I expect to release in the next couple of months.

Also you may be interested in the *self* type as it pertains to extension methods, check it out [here](http://manifold.systems/docs.html#self--extensions).

**Comment by rsmckinney** [comment] 2019-03-31 05:51
Duplicate of #7

**Closed by rsmckinney** 2019-03-31 05:51 UTC
