### ISSUE TITLE
Use of Structural interfaces triggers java module exception (java.lang.IllegalAccessException: class manifold.util.ReflectUtil$MethodRef cannot access class jdk.internal.module.Modules)

### ISSUE THREAD

**Issue by ghilainm** [manifold-systems/manifold#361] opened 2022-05-13 10:24 UTC
**Describe the bug**
I am using manifold-ext with Structural interfaces.

I am not using java modules.

**To Reproduce**
1. Create a interface with @Structural
2. Create a class which implement the structural interface
3. Invoke a method which takes as parameter the structural interface passing as parameter the class which implements the structural interface

**Expected behavior**
No exception.

**Desktop (please complete the following information):**
- OS Type & Version: 
- Java/JDK version:openjdk 11.0.14.1 2022-02-08 IBM Semeru Runtime Open Edition 11.0.14.1 (build 11.0.14.1+1)

- IDE version (IntelliJ IDEA or Android Studio): Build #IU-221.5591.52, built on May 10, 2022
- Manifold version: 2022.1.12
- Manifold IntelliJ plugin version: None

**Stack trace**

java.lang.IllegalAccessException: class manifold.util.ReflectUtil$MethodRef cannot access class jdk.internal.module.Modules (in module java.base) because module java.base does not export jdk.internal.module to unnamed module @bda0cd05
java.lang.RuntimeException: java.lang.IllegalAccessException: class manifold.util.ReflectUtil$MethodRef cannot access class jdk.internal.module.Modules (in module java.base) because module java.base does not export jdk.internal.module to unnamed module @bda0cd05
	at manifold.ext.rt.RuntimeMethods.createNewProxy(RuntimeMethods.java:404)
	at manifold.ext.rt.RuntimeMethods.constructProxy(RuntimeMethods.java:67)

**Comment by rsmckinney** [comment] 2022-05-15 04:00
Hi @ghilainm. I'm having trouble reproducing this issue. Can you provide a sample project that exhibits this?  Or perhaps just a build file (gradle/maven) that can be used as a basis?  Thanks.

**Comment by ghilainm** [comment] 2022-05-16 12:14
@rsmckinney Did you use the same JVM as me?

Here you are for the demo project -> https://github.com/ghilainm/manifold-bug-361

Just launch the main.

**Comment by rsmckinney** [comment] 2022-05-17 19:19
Thanks for the demo project.  The issue is specific to the IBM JVM and is now fixed.

Fix available with release 2022.1.14

**Closed** 2022-12-25 03:03 UTC
Labels: bug
