### ISSUE TITLE
All versions 1.6, 1.7, and 1.8 after version 2024.1.5 are not available

### ISSUE THREAD

**Issue by zcfire2017** [manifold-systems/manifold#556] opened 2024-03-16 01:04 UTC
After version 1.5, the build project keeps reporting errors.

[ERROR] /D:/work/java/kc-ocm-server/base/src/main/java/com/base/util/system/enums/IntEnum.java:[6,4] Unable to access com.base. util.system.enums.IntEnum
   Wrong source file: D:\work\java\kc-ocm-server\base\src\main\java\com\base\util\system\enums\IntEnum.java
     File does not contain class com.base.util.system.enums.IntEnum
     Please delete the file or ensure that the file is in the correct source path subdirectory.

[ERROR] /java/util/Map.java:[5,7] Unable to access java.util.Map
   Wrong source file: java/util/Map.java
     File does not contain class java.util.Map
     Please delete the file or ensure that the file is in the correct source path subdirectory.

**Comment by zcfire2017** [comment] 2024-03-16 01:05
IntelliJ IDEA 2023.3.5 (Ultimate Edition)
Build #IU-233.14808.21, built on March 12, 2024

manifold plugin version 2023.3.19

**Comment by rsmckinney** [comment] 2024-03-16 01:13
Others have found this issue too. Are you using Lombok?  Will have a fix asap... ~later tonight.  Thanks for reporting.

**Comment by rsmckinney** [comment] 2024-03-16 02:06
Duplicate of https://github.com/manifold-systems/manifold/issues/555

**Closed by rsmckinney** 2024-03-16 02:06 UTC
Labels: duplicate
