### ISSUE TITLE
Inconsistency in extension method

### ISSUE THREAD

**Issue by WilliamStone** [manifold-systems/manifold#48] opened 2019-02-28 23:22 UTC
In my eyes extension method is just a syntax sugar. so if a non-extension method works, so sould extension method. And I found some cases that violates above principle.

```
package ir.mohaymen.analytics.utilities.extensions.java.util.List;

import manifold.ext.api.Extension;
import manifold.ext.api.This;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Function;

@Extension
public class MyListOfStringExt {
  public static <P, T extends List<P>, R> R let4(@This List<P> thiz, Function<T, R> mapper) {
    return mapper.apply((T) thiz);
  }

  public static void test() {
    List<String> x = new ArrayList<>();

    String x1 = x.let4(it -> it.get(0));  // Doesn't compile: Bad return type in lambda expression: P cannot 
                                              // be converted to Object 
    String x2 = let4(x, it -> it.get(0)); // Works

    Integer x3 = x.let4((List<String> it) -> it.size()); // Doesn't compile: no instance(s) of type variable(s) 
                                                           //exist so that List<String> conforms to List<P>
    Integer x4 = let4(x, (List<String> it) -> it.size());  // Works

  }
}
```

manifold version: 0.45-alpha
JDK version: 11.0.2

**Comment by rsmckinney** [comment] 2019-03-01 01:21
Manifold currently does not support extension method _specialization_.  For instance, you can only extend `List`, not `List<String>`.  Good news, this feature is in the backlog and will be supported soonish -- perhaps within a couple of months.

**Comment by WilliamStone** [comment] 2019-03-01 03:01
Thanks, glad to hear that!

**Comment by rsmckinney** [comment] 2019-03-30 19:29
duplicate of https://github.com/manifold-systems/manifold/issues/7

**Closed** 2019-03-30 19:28 UTC
Labels: enhancement
