### ISSUE TITLE
When using param in manifold-templates, Idea reports that param may not have been initialized

### ISSUE THREAD

**Issue by moheng233** [manifold-systems/manifold#588] opened 2024-05-11 01:35 UTC
**Describe the bug**
When using param in manifold-templates, Idea reports that param may not have been initialized

**To Reproduce**
I used the following code to demonstrate the bug
```mtl
<%@ params(String param1) %>

Hello ${param1} test

<%if (param1 == "1") {%>
<%}%>
```
Such code will report an error in idea: param1 may not be initialized.
Although the compilation is fine, the idea's error reporting still affects the enjoyment of the development.

**Screenshots**
![image](https://github.com/manifold-systems/manifold/assets/57742561/d9b8f183-569c-4cc3-924c-0b380956ae18)
> I'm Chinese for this, so please don't mind my Chinese screenshots. But the reported error is the same as described above.

**Desktop:**
- OS Type & Version: Windows11
- Java/JDK version: JDK21
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ IDEA 2024.1.1
- Manifold version: 2024.1.14
- Manifold IntelliJ plugin version: 2021.1.0

**Comment by rsmckinney** [comment] 2024-05-14 03:42
Hi @moheng233. Sorry for the wait. This issue is specific to the Chinese (Simplified) Language Pack / 中文语言包. Manifold has a lot of the Chinese translations covered, but still more to go. This issue will be fixed along with many other translation related fixes within a couple of days when the next Manifold IntelliJ plugin is released.  Thanks for your patience.

**Comment by moheng233** [comment] 2024-05-14 07:39
The language pack is not the cause of the error, because when I uninstall the language pack, it still has the error.
![image](https://github.com/manifold-systems/manifold/assets/57742561/6e4455c6-3de2-425a-9550-403d1073a83a)

**Comment by rsmckinney** [comment] 2024-05-14 13:35
I can't reproduce this. Although, the sample you have will produce a different error because your template example uses a  statement, but should instead use an expression: use `<%= param1 %>` or `${param1}`.

In any case, regarding the Chinese lang pack use, I am positive that's the cause of the error. Lang pack related changes are ready that will be included in the next plugin release tomorrow.

**Comment by moheng233** [comment] 2024-05-15 00:38
I appreciate your response. I will await the next iteration of the software, as I am particularly interested in your work. It is encouraging to see improvements being made to the shortcomings of Java, and it is also beneficial to note that it works well with lombok.

**Comment by rsmckinney** [comment] 2024-05-15 00:59
Nice to hear, thank you very much.

**Comment by rsmckinney** [comment] 2024-05-15 23:58
Fix available with latest plugin release.

Here you can see a sample template file open with Chinese Language Pack installed. Notice no errors on the param reference.

![image](https://github.com/manifold-systems/manifold/assets/588843/f693c564-2a6f-441e-ac25-930f857ac714)

**Closed** 2024-05-20 13:50 UTC
