### ISSUE TITLE
Unable to use Github GraphQL Schema

### ISSUE THREAD

**Issue by dbowles** [manifold-systems/manifold#100] opened 2019-06-19 10:04 UTC
**Describe the bug**
Manifold is not able to handle Unicode characters in a GraphQL schema

**To Reproduce**
1. Take the public GitHub schema from https://developer.github.com/v4/public_schema/schema.public.graphql
2. Add to project and try to compile

**Expected behavior**
I would have expected schema to be parsed correctly

**Desktop (please complete the following information):**
- OS Type & Version: OSX 10.14.4
- Java/JDK version: 1.8
- IntelliJ IDEA version: 2019.1.3
- Manifold version: 2019.1.4
- Manifold IntelliJ plugin version: 2019.1.2 

**Additional context**

**Stack trace**
line 19062:4 token recognition error at: '"\n'
line 19063:17 token recognition error at: '😕'
line 19063:24 token recognition error at: '.\n'
line 19068:17 token recognition error at: '👀'
line 19068:24 token recognition error at: '.\n'
line 19073:17 token recognition error at: '❤'
line 19073:18 token recognition error at: '️'
line 19073:25 token recognition error at: '.\n'
line 19078:17 token recognition error at: '🎉'
line 19078:24 token recognition error at: '.\n'
line 19083:17 token recognition error at: '😄'
line 19083:24 token recognition error at: '.\n'
line 19088:17 token recognition error at: '🚀'
line 19088:24 token recognition error at: '.\n'
line 19093:17 token recognition error at: '👎'
line 19093:24 token recognition error at: '.\n'
line 19098:17 token recognition error at: '👍'
line 19098:24 token recognition error at: '.\n'
line 19104:23 token recognition error at: '.\n'
line 19108:32 token recognition error at: '.\n'
line 19113:33 token recognition error at: '.\n'
line 19119:59 token recognition error at: '.\n'
line 19123:31 token recognition error at: '.\n'
line 19128:42 token recognition error at: '.\n'
line 19133:33 token recognition error at: '.\n'
line 19142:73 token recognition error at: '.\n'
line 19147:74 token recognition error at: '.\n'
line 19152:48 token recognition error at: '.\n'
line 19157:47 token recognition error at: '.\n'

**Comment by rsmckinney** [comment] 2019-06-19 18:50
Hi @dbowles.  

The root cause appears to be the graphql parser manifold uses does not handle unicode characters such as emoji in comments.  I've logged https://github.com/graphql-java/graphql-java/issues/1577 for them, hopefully this is an easy fix in their antlr grammar.

Thanks for report this!

**Comment by dbowles** [comment] 2019-07-01 06:46
thank you @rsmckinney for the prompt response.  As a workaround, I've manually removed the Unicode characters.

**Comment by rsmckinney** [comment] 2019-08-16 01:05
Fixed with https://github.com/graphql-java/graphql-java/pull/1603

**Closed by rsmckinney** 2019-08-16 01:05 UTC
Labels: bug
