### ISSUE TITLE
[BUG] Unexpected behavior around generic types in extension method's `@This` parameter

### ISSUE THREAD

**Issue by CC007** [manifold-systems/manifold#498] opened 2023-09-16 15:02 UTC
**Describe the bug**
Wrong method is attempted to get called, due to generics being ignored in an extension method.

**To Reproduce**
1. Create `streamIndexed` and `filterIndexed` extension method in the `IterableExt` class (see screenshot)
2. Create `map` extension method with `@This Stream<Indexed<T>>` and `IndexedFunction<T, R>` parameter in `StreamExt` (see last screenshot)
3. Use the `map` extension method (see first screenshot)

**Expected behavior**
The ability to use the extension method without error,
The method I'm expecting to call is `Stream<R> map(IndexedFunction<Boolean, R> mapper)`, rather than `Stream<R> map(IndexedFunction<Indexed<Boolean>, R> mapper)`

**Screenshots**
![afbeelding](https://github.com/manifold-systems/manifold/assets/5381337/21e00e93-36ea-4708-b75b-5f773a1844bb)
![afbeelding](https://github.com/manifold-systems/manifold/assets/5381337/0ad66c4a-ce31-4616-b16f-d8f17d8a0858)
![afbeelding](https://github.com/manifold-systems/manifold/assets/5381337/1b16279e-dc33-4216-8401-7208ab3be6ea)
![afbeelding](https://github.com/manifold-systems/manifold/assets/5381337/dc8b3a03-9001-4791-9282-27e38a31b2c4)
![afbeelding](https://github.com/manifold-systems/manifold/assets/5381337/82e8a6a5-5c97-4d90-813f-6ef762d4edc0)
![afbeelding](https://github.com/manifold-systems/manifold/assets/5381337/d5c830f1-cfdf-4abd-97e0-230cce0f90af)

**Desktop (please complete the following information):**
- OS Type & Version: Windows 10
- Java/JDK version: openjdk-20.0.2
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ 2023.2.2
- Manifold version: 2023.1.25
- Manifold IntelliJ plugin version: 23.1.25

**Additional context**
`Indexed<T>` is defined like this:
![afbeelding](https://github.com/manifold-systems/manifold/assets/5381337/71d3bc8f-0785-4f38-b872-168a17e35d7a)

**Workaround**
As a workaround, I can define a `Function<Indexed<T>,R>` rather than an `IndexedFunction<T, R>` and call the normal `Stream.map(...)` method instead of my extension method, however it would be nice if the extension method worked too.

**Comment by CC007** [comment] 2023-09-17 09:58
To make sure that this wasn't an issue with overloading the existing `Stream.map(Function<T, R> mapper)` method, I renamed the extension method (for instance to `mapIt(...)`. The issue still persisted.

**Comment by rsmckinney** [comment] 2023-09-18 03:58
@CC007 this is a known issue. I should carve some time out and implement this, relatively simple to implement.

Duplicate of https://github.com/manifold-systems/manifold/issues/7

**Closed by rsmckinney** 2023-09-18 03:58 UTC

**Comment by CC007** [comment] 2023-09-18 04:13
I also noticed that I have to use the same generic type name as was used in the original class definition (so `T` for `Iterable` and `E` for `Set`), otherwise I'd get a compilation error. Does that also have to do with #7?
