### ISSUE TITLE
IntelliJ plugin does not play nice with Lombok

### ISSUE THREAD

**Issue by 54** [manifold-systems/manifold#42] opened 2019-01-27 16:26 UTC
**Describe the bug**

The issue appears to be that the IntelliJ plugin always adds the "-processorpath" flag to the IntelliJ javac params. This causes javac to not check the rest of the classpath for additional annotation processors, like Lombok. 

I didn't have time today to check as to whether or not this also occurs in single-module Gradle projects, but I can confirm this is an issue on multi-modular ones, at least.

**To Reproduce**

1. Create a new Gradle project
2. Create a subproject with Manifold as a compile and annotationProcessor dependency along with Lombok as a compileOnly and annotationProcessor dependency
3. Import the project as a Gradle project in IntelliJ
4. Install the Manifold and Lombok plugins to IntelliJ
5. Enable annotation processing on the project
6. Create a class using some Lombok features (e.g., @Getter)
7. Create a class using Manifoold features, like an extension method
8. Compile and watch as javac successfully processes the Manifold annotations, yet fails to handle Lombok

**Expected behavior**

I expect the plugin to not add the '-processorpath' parameter when Manifold is already specified as an annotation processor in Gradle.

**Screenshots**

N/A

**Desktop (please complete the following information):**
- OS Type & Version: Windows 10 LTSC 1809
- Java/JDK version: 11.0.1
- IntelliJ IDEA version: 2018.3.3
- Manifold version: 0.39-alpha
- Manifold IntelliJ plugin version: 0.39-alpha
- Gradle version: 5.1

**Additional context**

N/A

**Stack trace**

N/A

**Comment by rsmckinney** [comment] 2019-02-01 18:07
in progress

**Comment by rsmckinney** [comment] 2019-02-02 03:43
Should be fixed with Manifold release v0.41-alpha.  A new plugin release (0.41-alpha) is pending JetBrains repo approval, usually takes a day to two.  Or download it from: https://plugins.jetbrains.com/plugin/10057-manifold.

I reproduced the same problem with a similarly configured Maven project.  The issue is not related to the IJ processor path UI, rather it is related to Manifold compiler plugin internals -- the Gradle or Maven project files settings override the UI settings during a JPS build.  *Should* be cleared up now. Let me know otherwise.

**Comment by rsmckinney** [comment] 2019-02-19 16:16
Hi Omar.  Please let me know if your issue if fixed, or if there is anything else I can do here. Thanks.

**Closed** 2019-02-21 08:13 UTC
Labels: bug
